### ISSUE TITLE
Bug: wrapped lines get skipped when navigating with up/down arrow keys

### ISSUE THREAD

**Issue by Elmari** [FXMisc/RichTextFX#1071]
I noticed a strange behavior when using non-textual segments in combination with line wrapping: Sometimes multiple lines of a paragraph are skipped or the caret won't go to the next line when navigating with the up/down arrow keys.
This can be reproduced with the richtext demo in the demo folder. Just place some images within the text and try to go up and down with the arrow keys:

![ezgif-5-022871144a](https://user-images.githubusercontent.com/1381848/149622581-aa2955cf-8a7c-4365-886e-b928cf8544d8.gif)

(When pressing arrow down the caret stopped at the line with the e's and the caret had to be placed manually with the cursor.)
Please let me know if the gif is descriptive and clear enough. Otherwise I'll be happy to create a new one.

## Environment info:

- RichTextFX Version: 0.10.7
- Operating System: Windows 11
- Java version: Java 17
- Tested with JavaFX version: 11 / 17

**Comment by Elmari** [comment]
This is apparently because the number of lines in TextFlowLayout#getLineCount is not calculated correctly. If I change line 85,86 from:
```
if ( nodeMinY >= prevMinY && lines > 1 )  totLines += lines - 1;  // Multiline Text node 
else if ( nodeMinY >= prevMaxY )  totLines += lines;
```
to 

```
if (nodeMinY >= prevMaxY) totLines += lines;
else totLines += lines - 1;
```
it does work correctly. 

However, I don't know if this is the ideal solution yet, or if this will bring side effects.

**Comment by Jugen** [comment]
Hey @Elmari,  I've tried to replicate the problem but so far without success ?

![image](https://user-images.githubusercontent.com/5031427/150489916-81df56ed-7794-4bcd-8b18-fb516134a0dc.png)

This appears identical to yours apart from the images inserted. I can navigate without getting stuck or skips ?

However I have given your code change some thought and I think it would be okay to change it.
Could you try the following (for code clarity) and let me know if this works for you:

```java
if ( nodeMinY >= prevMaxY )  totLines += lines;
else if ( lines > 1 )  totLines += lines - 1; 
```

Ideally though it would be nice to figure out what's going on and not shooting in the dark like this :-)
Could you try putting a break point in [TextFlowExt.hitLine( x, line )](https://github.com/FXMisc/RichTextFX/blob/6f8cec7ccff30d27147f06c3b379418bc1a85037/richtextfx/src/main/java9/org/fxmisc/richtext/TextFlowExt.java#L101) and activating it when on the eeeee line, then press down arrow and step through the code to figure out what's happening. It may be that the problem is with _getLineCenter_ or maybe with _if (y >= span.getBounds().getMaxY())_ a few lines down at 112 ?

**Comment by Elmari** [comment]
Hey @Jugen, thanks for your answer. Your code snippet works as well.
I just tried around with different dpi settings: If I lower my system DPI setting from 125% to 100%, the problem no longer occurs even with the original code.
Also, when using 125% dpi, the skipping of lines always occurs, but the "caret not going down" problem sometimes only occurs if I resize the window. Maybe that helps to replicate the problem.
I'll get back to you later with the debugging results

**Comment by Elmari** [comment]
Debugging-Results:

hitLine does not get called at all when in the line where the caret doesn't move down as apparently `currentLine` is the same as `targetLine`. Maybe because the number of lines are already calculated wrongly?

Also, the line number is not calculated correctly because sometimes nodeMinY is not exactly equals to prevMinY. I added a simple output as an example:

NodeMinY: 21.0; prevMinY: 21.33333396911621
No line added although line count is 4.0

**Comment by Jugen** [comment]
I've looked further into this and can confirm the bug manifests at DPI 125%. What happens is that there seems to be some relative variation in what _node.getBoundsInParent()_ returns at different DPI settings, so then `nodeMinY >= prevMinY` fails to detect additional staggered multi-line text. After more thought I'm fairly confident that your suggestion of inverting the test essentially results in the same outcome and so have submitted a PR with our combined code changes.

**Comment by Elmari** [comment]
Thanks for your quick reply. The PR looks good to me.
