### ISSUE TITLE
GenericStyledArea adding inappropriate character when using a different keyboard setup

### ISSUE THREAD

**Issue by garybentley** [FXMisc/RichTextFX#1205]
This is a bit of a weird one and I suspect it has nothing to do with GenericStyledArea but instead relates to the underlying JavaFX text handling, anyway...

On Windows 10, if you set the keyboard to be "Scottish Gaelic" then in the GenericStyledArea type ' and then type a vowel, i.e. a, e, i, o u it should produce an accented version of that vowel, i.e. à, è, ì, ò, ù.  This is the behaviour seen in applications like Word.  However in GenericStyledArea the next character typed after the ' will always be accented, so typing 's will produce ś.  Instead of "he's" you get "heś".

If this a RichTextFX issue or JavaFX text handling issue?

**Comment by Jugen** [comment]
Hi Gary, had a quick look at [GenericStyledAreaBehavior](https://github.com/FXMisc/RichTextFX/blob/master/richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledAreaBehavior.java) and didn't see anything obvious.

I think this may be a JavaFX and Windows dead key issue. Although, it's weird because if I'm not mistaken the "Scottish Gaelic" keyboard layout doesn't have `ś` as a dead key output.

Anyway, you could try the `'s` key combination in a plain TextArea and see what it produces to check if this is a RichTextFX or JavaFX issue.

**Comment by garybentley** [comment]
Hi Jugen,

I tested JavaFX/TextArea and the behaviour is happening with that component so I think it's a JavaFX issue.

I'll close this.

**Comment by Jugen** [comment]
Thanks for the feedback.
