### ISSUE TITLE
Add support for autosizing the area based on its content

### ISSUE THREAD

**Issue by armin-bauer** [FXMisc/RichTextFX#171]
Hi,

it would be great if it was possible that the rich text edit automatically changes it's height, so that I can set a minimum and a maximum and the box just get's bigger as I enter text until the maximum is reached (could probably be done using maxHeight and minHeight). I'm trying to implement the feature myself for pull request but I didn't find out yet what would be the best way to do it since I've just recently started with JavaFX and don't know my way around everything yet.

If I'm missing something and this is already possible, please show me how. 

Thanks.

**Comment by TomasMikula** [comment]
Hi Armin,

this is not supported, because to compute the ideal height of the text area requires to layout the whole document, which would be costly for large documents (imagine thousands of paragraphs).

However, if maxHeight is given, it could be reasonable to try to compute the exact height, but once the intermediate value reaches the maxHeight limit, stop and return maxHeight.

If you want to give it a shot yourself, you need to start with [Flowless](https://github.com/TomasMikula/Flowless), which is a component that RichTextFX uses to efficiently layout paragraphs (i.e. only layout visible paragraphs).

**Comment by Jugen** [comment]
Closed via PR 944
