### ISSUE TITLE
CodeArea and setStyle(start,stop,style) doesn't work

### ISSUE THREAD

**Issue by halirutan** [FXMisc/RichTextFX#640]
We use the `CodeArea` in JabRef as text-editor for BibTeX sources. I was working on a highlighting parser when I noticed, that somehow `org.fxmisc.richtext.GenericStyledArea#setStyle(int, int, S)` doesn't work. I can use `setStyle` for the whole text successfully, but as soon as I try to style only a text-range, nothing is changed. I've created [a minimal example](https://gist.github.com/halirutan/87f5fe49ce681c488b812ff764d109fc)  that is based on the java-keywords code and can be run on its own (adjust the package header). 

There, I try to set the style for testing. The commented portion works, the text-range styling not

```
    @Override
    public void start(Stage primaryStage) {
        CodeArea codeArea = new CodeArea();
        codeArea.setParagraphGraphicFactory(LineNumberFactory.get(codeArea));
        codeArea.replaceText(0, 0, sampleCode);

//        codeArea.setStyle("-fx-font-weight: bold");
        codeArea.setStyle(0,30, Collections.singleton("-fx-font-weight: bold"));

        Scene scene = new Scene(new StackPane(new VirtualizedScrollPane<>(codeArea)), 600, 400);
        primaryStage.setScene(scene);
        primaryStage.setTitle("Java Keywords Demo");
        primaryStage.show();
    }
```

I'm on Linux with Java 1.8.0_144 and richtextfx:0.8.1. Is this supposed to work this way or am I doing something completely stupid?

**Comment by JordanMartinez** [comment]
> Is this supposed to work this way or am I doing something completely stupid?

Since you are using a `CodeEditor`, which subclasses `StyleClassedTextArea`, the `applyStyle` function works like this `(textExt, styleClass) -> textExt.getStyleClass().add(styleClass)`. However, you are passing inline css as the argument, not a style class. (Also, a better way to add style classes is `setStyleClass(int, int, S)` since the type for setStyle is `setStyle(int, int, Collection<S>)`)

`codeArea.setStyle` affects the style of the entire area, not an individual paragraph or section of it.

If you want to use both in your code, you'll need to use a custom `applyStyle` function like the one mentioned in the wiki. There's no section header to it, so [go to this page](https://github.com/FXMisc/RichTextFX/wiki/Text-Styles%3A-Inline%2C-Style-Class%2C-and-Custom-Style-Objects) and scroll to where it say "If you wish to use an approach that mixes the two, you should follow this pattern." It appears right above the "Style Class Pattern" header

**Comment by halirutan** [comment]
Thank you for replying in such detail. I'm trying this out.
