### ISSUE TITLE
Question: Easy way to get line number from caret position

### ISSUE THREAD

**Issue by liz3** [FXMisc/RichTextFX#698]
Hey, 
This is a super simple Question, does the Api somehow provide a way to get the current lineNumber the caret is on?
If not i will write me a simple helper method.

Regards,

Yann "Liz3" HN

**Comment by JordanMartinez** [comment]
[`area.getCaretSelectionBind().getLineIndex();`](https://github.com/FXMisc/RichTextFX/blob/70509b574f2a0b05015f69f4ce9da790a51a3537/richtextfx/src/main/java/org/fxmisc/richtext/Caret.java#L70-L72)

**Comment by liz3** [comment]
ok
thx a lot

**Comment by liz3** [comment]
ERROR: Does not work...
I am calling it in `area.caretPositionProperty().addListener` and the Optional int is present, but always returns 0

**Comment by Jugen** [comment]
I tried using `area.getCaretSelectionBind().lineIndexProperty().addListener()`  and it never gets invoked, which is consistent then with what liz3 reports.

**Comment by Jugen** [comment]
We have here a discrepancy between what the API seems to imply (user expectation) and what it actually does. So the method names (`getLineIndex` and `lineIndexProperty`) imply that you are going to get the currrent line index relative to the **area / document**, since that is what the method is being invoked on, but what is actually being calculated and returned is the index of the line relative to the current **paragraph**. Hence the above behavior and results.

**Comment by liz3** [comment]
Here is my helper method, im sure there are better ways, but its working,
NOTE: this shall refer to the CodeArea:
```
fun CodeArea.getCaretLine(): Int {
    var count = -1
    var lines = 1
    val split = this.text.toCharArray()
    while (count != this.caretPosition) {
        count++
        if (count == split.size) break
        if (split[count] == '\n') lines++
    }
    if (count < split.size && split[count] == '\n') lines--
    return lines
}
``` 

Regards
Liz3

**Comment by JordanMartinez** [comment]
The API works as it should work and @Jugen's explanation is correct. The problem was the terminology that @liz3 used. She used the terminology `line index` to refer to what we would call the `paragraph index`. So, I thought she was really asking for the line index on a multi-line paragraph (i.e. when the paragraph's text is wrapped and spans multiple lines), not the paragraph index. 

To get the area's main caret's current paragraph index, you can write `area.getCurrentParagraph();` or `area.getCaretSelectionBind().getParagraphIndex();` 

@liz3, have you read through the class-level javadoc of `GenericStyledArea` and the various `@see OtherClass` tags there at the bottom yet?

**Comment by Jugen** [comment]
Here is better way I think, Liz3 :-)

        area.caretPositionProperty().addListener( (ob,ov,nv) ->
        {
        	int curPar = area.getCurrentParagraph(), lineCount = 0;
        	for ( int p = 0; p < curPar; p++ ) {
        		lineCount += area.getParagraphLinesCount( p );
        	}
        	lineCount += area.lineIndex( curPar, area.getCaretColumn() );
        });

**Comment by liz3** [comment]
Yeah ok, sorry that i ask the wrong thing!
(Kotlin) `area.caretSelectionBind.paragraphIndex`

Thank you very much

**Comment by Jugen** [comment]
There's no need to apologize, you didn't ask the wrong thing !

**Comment by JordanMartinez** [comment]
@liz3 Jugen's right. It's not your fault and there's no need to apologize. It was simply a miscommunication and I also misunderstood you. Please, don't feel like you cannot ask other such questions in the future.
