### ISSUE TITLE
How to remove the rectangles around selected lines ?

### ISSUE THREAD

**Issue by alexdiostia** [FXMisc/RichTextFX#738]
Hello
new to RichTextFX... looks great!
Is it possible to remove the "line boxing" when selecting text over multiple lines ?
it looks weird to have each line separately surrounded by those rectangles..
thanks !
alex

**Comment by JordanMartinez** [comment]
Which version of RTFX are you using? Which flavor of `GenericStyledArea` are you using? What's your CSS for the `selection` style class? Can you provide a screenshot of the issue so I'm sure I'm understanding you correctly?

In short, if you change the `selection`'s style class to something else, it should get rid of the 'line boxing' you're talking about (unless you're referring to something like #683)

**Comment by saifalmutory** [comment]
do you mean this?
![1](https://user-images.githubusercontent.com/38837773/40068450-507a79da-5871-11e8-88f2-bb16e3632891.PNG)
Well I'm having the same problem.

**Comment by saifalmutory** [comment]
I think the reason is use:
`getStylesheets().clear();`
For this reason the style should not be cleared.

**Comment by bezvaapp** [comment]
This problem happens on RichTextFX 0.10.2 OpenjFX 13.0.1  OpenJDK 13.0.1. Windows 7

When a selection is started with a mouse and the mouse keeps dragging until the scrollbar moves automatically to show the next part of the document then suddenly small space appears between the lines and the selection is no longer solid but has these tiny lines.

It does not happen when you select using keys because the selection with keys is growing line by line.
With mouse the selection jumps several lines when the edge of the visible part of the document is reached.
