### ISSUE TITLE
Error: When I set style to the second line, I get IndexOutOfBoundsException

### ISSUE THREAD

**Issue by saifalmutory** [FXMisc/RichTextFX#741]
`seText` is `InlineCssTextArea`
Here I try to set the style by selecting the first line :
`seText.setStyle(seText.getCurrentParagraph(),seText.getSelection().getStart(),seText.getSelection().getEnd(),ControlColorPane.getSelectedColor());`
`System.out.println(seText.getSelection());`
I get good results
![capture](https://user-images.githubusercontent.com/38837773/39659841-63f22b64-503a-11e8-9b64-246c648b798d.PNG)

Output : 0, 5
But when I select the second line ans try changing the color
![capture2](https://user-images.githubusercontent.com/38837773/39659865-eca2d490-503a-11e8-8f1e-6867b75fcecc.PNG)
Get `Caused by: java.lang.IndexOutOfBoundsException: [6, 11) is not a valid range within [0, 5)`
Output : 6, 11
and the style does not change either

**Comment by JordanMartinez** [comment]
Based on that error message, I believe you're passing in the wrong arguments...
````java
public void setStyle(int paragraphIndex, int columnPositionStart, int columnPositionEnd) {}
````
`columnPositionStart` and `columnPositionEnd` expect to be a value `x` that is `0 <= x <= area.getParagraphLength(paragraphIndex)`. 

However, you're passing in `seText.getSelection().getStart()` and `seText.getSelection().getEnd()`. This issue does not occur in the first example because the selection **just happens** to be the same values as the one you need (i.e. the start position is 0 and the end position is equal to the paragraph length). However, once you add another line, that is no longer the case. Your start position is in terms of the area's position, not the paragraph's position.

You should just use `area.setStyle(getSelection().getStart(), getSelection().getEnd(), style)`
