### ISSUE TITLE
Does RTFX provide events?

### ISSUE THREAD

**Issue by saifalmutory** [FXMisc/RichTextFX#747]
I need to know the change in `InlineCssTextArea`
For example: I want to know the change in the height of the text,
There is some code that must be executed whenever the height of the text changes.
Using the key event and checking the ctrl and enter is a bad idea.
I need those events
Any ideas? I will be grateful

**Comment by JordanMartinez** [comment]
The only changes that occur in RTFX are those via `multiPlainTextChanges`/`multiRichTextChanges`/`plainTextChanges`/`richTextChanges` and all other Properties found in `GenericStyledArea` (e.g. `wrapTextProperty()`). 
There isn't a change event specifically for the height of the text because it's hard to know when that changes. The best you could do is use two or more style classes specifically for a text's height and then register a change in the area's style spans whenever one of those style classes gets changed to another.

**Comment by saifalmutory** [comment]
Cases where text height changes are not few:
1. Change in font size
3.Change in padding (top, bottom, right, left, between text)
3. Cut and paste
This makes it harder

**Comment by saifalmutory** [comment]
What about providing more events?

**Comment by JordanMartinez** [comment]
> Change in font size

Font size is currently controlled via a CSS style (whether that be `area.setStyle(String)` or `area.getStyleClass().add(String)`. If you want such an event, you can create it yourself by building on top of RTFX.

> Change in padding (top, bottom, right, left, between text)

Assuming you don't mean #749, this is not currently supported. Feel free to submit a PR.

> Cut and paste

Once you get the above two done, I don't see why this would be hard since the cut and paste would trigger the necessary changes/events, correct?

**Comment by saifalmutory** [comment]
yes ,I got what I want ,Thank you
