### ISSUE TITLE
Question: disabling new line functionality (pressing return)

### ISSUE THREAD

**Issue by SkyAphid** [FXMisc/RichTextFX#763]
I'm using a InclineCssTextArea as a basic field, but the problem is the new line functionality doesn't seem customizable. I know I can just use TextField, but one of the reasons why I chose RichTextFX is because it can handle special characters like heart symbols automatically if the font doesn't have them by default. So I don't have any choice but to use your text areas.

![capture](https://user-images.githubusercontent.com/6147299/42122747-4858932c-7c0c-11e8-914b-6e86608f8212.PNG)

To summarize, how do I prevent being able to press enter and start a new line on a text area like this? It needs to remain in one line forever. I already have setWrapText(false) on the area.

[I saw this, but I was wondering if any progress had been made on it, or if you guys can make a workaround.](https://github.com/FXMisc/RichTextFX/issues/635) I really need the special character handling of RichTextFX, so there's not an alternative for me unless I remove that functionality, which is very bad because my software is for video games, which tend to need those characters for creative reasons. I'm okay with something like overriding the button listener to disable it, or something equally hacky like that for now until you guys make a proper system for it.

Thanks!

**Comment by JordanMartinez** [comment]
Check the [Override Default Behavior demo](https://github.com/FXMisc/RichTextFX/blob/master/richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/OverrideBehaviorDemo.java) that I mentioned in my reply to that issue. Also look at [the default behavior](https://github.com/FXMisc/RichTextFX/blob/master/richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledAreaBehavior.java) for understanding the same pattern there and how to use `InputMapTemplate` for better memory usage.

Essentially, you're going to override [this behavior](https://github.com/FXMisc/RichTextFX/blob/master/richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledAreaBehavior.java#L67) with something like:
````java
InputMapTemplate.consume(EventPattern.keyPressed(KeyCode.Enter))
````

Follow the pattern and simply consume the `Enter` so it does nothing.

Also, please open a new issue requesting a `RichTextField` feature since, I believe, that should also fall in this project.

**Comment by SkyAphid** [comment]
Thanks, for anyone else who needs this, here's the utility function I ended up making:

```
public static void disableMultiLineShortcuts(InlineCssTextArea area) {
	InputMap<Event> map = InputMap.consume(anyOf(keyPressed(ENTER, SHORTCUT_ANY, SHIFT_ANY)));
	Nodes.addInputMap(area, map);
}
```
