### ISSUE TITLE
Question: Binding CodeArea to ObservableList

### ISSUE THREAD

**Issue by bytecod3r** [FXMisc/RichTextFX#797]
Hi,,

Trying to figure out how to bind RickTextFX to another Observable-list, the below code belongs to JavaFX TextArea, I want to know if there is any equivalent in RichTextFX? Thanks

`textArea1.textProperty().bind(this.class.class1_TerminalDataProperty());`

**Comment by Jugen** [comment]
You can try the following:

`Bindings.createStringBinding( () -> textArea1.getText(), textArea1.textProperty() );`

**Comment by Jugen** [comment]
You can try the following:

`terminalDataProperty().addListener(cl -> richtext.replaceText(terminalDataProperty().get()));`

Although if your terminal data has lots of text and is continuously updating then it might of course be better to rather apply just the changes to the RichTextFX area, instead of using replaceText as above.

**Comment by bytecod3r** [comment]
Thanks, its working.
