### ISSUE TITLE
Dvorak keyboard on OSX not supported when doing cut and paste CMD-V, etc

### ISSUE THREAD

**Issue by zcaudate** [FXMisc/RichTextFX#799]
When CMD-C, X, V, A, etc... is pressed while the keyboard is on Dvorak, it does not work as expected but goes back to the original Qwerty Keys

'C' for Dvorak maps to Qwerty `I` key, `CMD-C` is actually `CMD-I`
'V' for Dvorak maps to Qwerty `.` key, `CMD-V` is actually `CMD-.`
'X' for Dvorak maps to Qwerty `B` key, `CMD-X` is actually `CMD-B`

To get it working, `CMD-'QWERTY-C'` has to be used whilst on Dvorak.

**Comment by Jugen** [comment]
I think this is related to [https://bugs.openjdk.java.net/browse/JDK-8090257](https://bugs.openjdk.java.net/browse/JDK-8090257)

**Comment by dgelessus** [comment]
Similar issue here with the German QWERTZ layout. The shortcut for "Undo" should be Cmd+Z, but I have to press Cmd+Y (which would be Cmd+Z on a QWERTY keyboard).

I think the issue is not JavaFX, but rather that the undo/redo shortcuts are bound by key *code* (i. e. physical key) rather than key *character*:

https://github.com/FXMisc/RichTextFX/blob/567e7e858ea08920895697c74302592fe800c909/richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledAreaBehavior.java#L70-L73

Replacing the uses of `Z` and `Y` (which are `KeyCode` constants) with `"Z"` and `"Y"` (strings) should make the key combination dependent on the character instead of the code. The same applies to the other key combinations that involve letters (Cmd+A, +X, +C, +V).

**Comment by Jugen** [comment]
@dgelessus yes I agree. That seems to have been the workaround for this problem with regards to AWT key events.
See: [[macosx] Dvorak keyboard mapping not honored when CMD/CTRL key pressed](https://bugs.openjdk.java.net/browse/JDK-8066068)

**Comment by Jugen** [comment]
@zcaudate and @dgelessus Could you both please try the following [simple program](https://gist.github.com/Jugen/fd68ebd3f1e0fb36fd7a1c6fd6b67c54) with your respective keyboard layouts and give me feedback please.

**Comment by dgelessus** [comment]
@Jugen The test program recognizes the keys based on my selected layout, i. e. pressing Cmd and the German Z key (i. e. the English Y key) is recognized as Undo. This is the behavior that I would also expect in the RichTextFX editor.

**Comment by zcaudate** [comment]
@Jugen I believe this fixes the issue.

**Comment by Jugen** [comment]
Ok, I'll try and do a PR based on this in the next few days ....

**Comment by Jugen** [comment]
There's a proposal to change from `KeyCharacterCombination` to `KeyCodeCombination` (see #1253), which could affect Dvorak and German keyboard users.

I've updated the RichTextFX maven 1.0.0-SNAPSHOT for testing. If possible please test and provide feedback.

**Comment by dgelessus** [comment]
I can't test the SNAPSHOT version of RichTextFX right now. But I can confirm that at least on macOS with JavaFX 23, pressing Cmd+Z with a German keyboard layout now generates `KeyCode.Z`, and not `KeyCode.Y` like before. It seems that the behavior was changed in JavaFX 21 (released in 2023, multiple years after this issue and fix) - see OpenJDK issue [JDK-8150709](https://bugs.openjdk.org/browse/JDK-8150709).

I don't have time to test this in detail right now, but I assume if you change the `KeyCharacterCombination` back to `KeyCodeCombination`, it will work as expected on JavaFX 21 or newer, but will re-introduce the problems for German, Dvorak, etc. on older JavaFX versions. This is probably an acceptable tradeoff if Russian, etc. keyboard layouts are completely broken without the change.
