### ISSUE TITLE
Memeory leak of CodeArea

### ISSUE THREAD

**Issue by TRUEJASONFANS** [FXMisc/RichTextFX#814]
![Capture2_CodeArea](https://user-images.githubusercontent.com/5670289/56629517-2ee33500-6680-11e9-850b-503f48d287e8.PNG)

The screenshot is the memory leak path of CodeArea. The object won't be collected since it was finally hold by root object. Can we use the weak reference in listener so that it won't hold by the root object although the leak is not serious.
PatternConstrainCodeArea is class extends CodeArea and we use the richtextfx-fat-0.9.03 jar.
I use the openjdk1.8.0_191 and openjfx1.8.0_191

**Comment by Jugen** [comment]
Just out of curiosity could you please check this with 0.9.2 (which had weaklisteners) and let me know what the results are - thanks.

**Comment by JFormDesigner** [comment]
Tried to reproduce the memory leak with following simple test program (using RichTextFX 0.10 and Oracle Java 8u192 on Windows):
~~~java
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;
import org.fxmisc.richtext.CodeArea;

public class MemoryLeakTest extends Application {

    @Override
    public void start(Stage primaryStage) throws Exception {
        Button closeButton = new Button("Remove CodeArea");

        CodeArea area = new CodeArea("abc\ndef");

        VBox box = new VBox(closeButton, area);

        closeButton.setOnAction(e -> box.getChildren().clear());

        Scene scene = new Scene(box, 400, 400);
        primaryStage.setScene(scene);
        primaryStage.show();
    }

    public static void main(String[] args) {
        launch(args);
    }
}
~~~

After starting the program, I did some typing, then hit the "Remove CodeArea" button and looked at a heap dump in VisualVM, but the instance count for `CodeArea` is zero. Which means that `CodeArea` was released.

So maybe the memory leak is somewhere else in your program (e.g. caused by some listeners) or the test program is too simple...

@TRUEJASONFANS Are you sure that you removed PatternConstrainCodeArea from the scene graph?

Your second screenshot shows that the node graph is referenced from field `Scene.dirtyNodes`, which strange because the references in `Scene.dirtyNodes` are removed on each pulse. Is your program stopped at a breakpoint?

**Comment by TRUEJASONFANS** [comment]
@JFormDesigner  @Jugen  
This is more details screenshot by jprofiler.
![code1](https://user-images.githubusercontent.com/5670289/56715016-02efae80-6769-11e9-980b-5b3d050ac385.PNG)
![code2](https://user-images.githubusercontent.com/5670289/56715018-04b97200-6769-11e9-9e13-bb08da96d20b.PNG)
![code3](https://user-images.githubusercontent.com/5670289/56715024-084cf900-6769-11e9-8041-8fa1377ff68f.PNG)

**Comment by TRUEJASONFANS** [comment]
@JFormDesigner 
I remove the node from scene graph by following way:
``` java
private static void disposeSceneGraph(Node root) {
    if (!Parent.class.isInstance(root)) {
      return;
    }
    for (Node node : Parent.class.cast(root).getChildrenUnmodifiable()) {
      if (node instanceof ImageView) {
        ImageView.class.cast(node).setImage(null);
        ImageView.class.cast(node).getProperties().clear();
      }
      if (node instanceof Pane) {
        Pane pane = Pane.class.cast(node);
        disposeSceneGraph(node);
        pane.getChildren().clear();
      }
      if (node instanceof SplitPane) {
        for (Node subNode : SplitPane.class.cast(node).getItems()) {
          if (subNode instanceof Parent) {
            disposeSceneGraph(subNode);
          }
        }
        SplitPane.class.cast(node).getItems().clear();
      }
      if (node instanceof ScrollPane) {
        disposeSceneGraph(ScrollPane.class.cast(node).getContent());
        ScrollPane.class.cast(node).setContent(null);
      }
      if (node instanceof TitledPane) {
        Node content = TitledPane.class.cast(node).getContent();
        disposeSceneGraph(content);
        TitledPane.class.cast(node).setContent(null);
        TitledPane.class.cast(node).setGraphic(null);
      }
      if (node instanceof BorderPane) {
        BorderPane borderPane = BorderPane.class.cast(node);
        disposeSceneGraph(borderPane.getLeft());
        disposeSceneGraph(borderPane.getRight());
        disposeSceneGraph(borderPane.getCenter());
        disposeSceneGraph(borderPane.getTop());
        disposeSceneGraph(borderPane.getBottom());
        borderPane.setLeft(null);
        borderPane.setRight(null);
        borderPane.setTop(null);
        borderPane.setBottom(null);
        borderPane.setCenter(null);
      }
      if (node instanceof TabPane) {
        TabPane tabPane = TabPane.class.cast(node);
        tabPane.getTabs().clear();
      }
    }
    if (root instanceof Pane) {
      Pane.class.cast(root).getChildren().clear();
    }
  }
````

**Comment by JFormDesigner** [comment]
@TRUEJASONFANS this code only removes all children from the given node, but it does not remove the node from its parent.

So if you use `disposeSceneGraph(myCodeArea)`, then the code area is **not** removed.

Use `parentOfCodeAreaPane.getChildren().remove(myCodeArea)` instead.

Generally it is not necessary to do such a recursive node removal. Only remove the top node, which removes the whole hierarchy.

Doing such recursive node removal may also have unpredictable side effects because it removes nodes that are internally used by controls (such as RichTextFX).

**Comment by TRUEJASONFANS** [comment]
@JFormDesigner  
I don't use disposeSceneGraph(myCodeArea).  disposeSceneGraph  method  is only invoked for my top root of scengraph when the widget should be disposed like close the window. 
I am not sure for the recursive node removal whether have the side effect and it's only invoked when the widget should be disposed so that it should be ok.

**Comment by TRUEJASONFANS** [comment]
![image](https://user-images.githubusercontent.com/5670289/56791921-e2902480-683a-11e9-87ca-add6a7ce0132.png)
@JFormDesigner  I found that there are always strong reference of parent will hold the upper object. Do you know how to remove its reference?

**Comment by JFormDesigner** [comment]
`parentOfCodeAreaPane.getChildren().remove(myCodeArea)` should change parent to null.

BTW if you use TabPane, then you can try to invoke `tab.setContent(null)` when removing a tab. This fixed a memory leak in Markdown Writer FX https://github.com/JFormDesigner/markdown-writer-fx/commit/b01e7add0a09aac6c04446bc2086aeeb5bf2f28a

**Comment by TRUEJASONFANS** [comment]
@JFormDesigner  I see. thanks.

**Comment by Jugen** [comment]
@JFormDesigner thanks for jumping in and helping :-)
BTW I thought the tab content leak problem had been fixed (I think with 8u20 ?), so I take it you are just being cautious or are you still experiencing a problem with tabs ?
