### ISSUE TITLE
Left and right key invalidation？

### ISSUE THREAD

**Issue by yanzhao77** [FXMisc/RichTextFX#830]
In InlineCssTextArea, I wrote a keyboard event monitor enter and backspace keys, and rolled back the input values on up and down keys, but the left and right keys were not monitored, but they failed. The two keys should have been moving cursors, but unfortunately, they do not work now, I would like to ask. How to restore it? And how to set the cursor position? This is my project address. You can open it for a try: https://github.com/yanzhao77/MakeCmdTest.

**Comment by Jugen** [comment]
I think setOnKeyPressed completely overrides InlineCssTextArea's key event processing, so instead of using `onKeyPressed="#onKeyPressedListener"` in FXML try using `loggerArea.addEventFilter( KeyEvent.KEY_PRESSED, this::onKeyPressedListener )` in Controller.java

Remember to consume the event if you don't want the InlineCssTextArea to process the key event further.
