### ISSUE TITLE
Question: How to scroll to selection in CodeArea?

### ISSUE THREAD

**Issue by prat-man** [FXMisc/RichTextFX#932]
Currently I am aware that we need to use `requestFollowCaret()` to scroll to caret.

However, I am not finding a solution for displaying the selected text (entirely if fits in viewport, otherwise partially).
For most cases it is working fine. However, sometimes, the selected text is just to the left of the viewport and scrolling a bit to the left reveals the highlighted text.

Is there some way I can make sure that the selected text gets displayed inside the viewport?

Here is a sample code of what I am doing right now:
```
codeArea.selectRange(start, end);
codeArea.requestFollowCaret();
```

I tried doing the following, but to no avail:
```
codeArea.moveTo(start);
codeArea.requestFollowCaret();

codeArea.selectRange(start, end);
```

The use of these selections, for me, is for a find (and replace) option as found in most text editors.

**Comment by Jugen** [comment]
Thanks, I'll submit a PR to address this.

BTW your _codeArea.moveTo(start);_ .... attempt can work but it requires a scene graph pulse to occur between it and _codeArea.selectRange(start, end);_ .... So like a 20ms delay needs to happen between the two, which is a pain.

An alternative which I haven't tried is to change the anchor position of the selection when needed. So if the next selection is to the left of the last selection [use `getParagraphSelection( parIdx )` to get the selection start & end relative to the paragraph] then select the word/phrase backwards so that the caret is at the start of the selection.

The above are just suggestions if you can't use the PR or wait until the next release.

**Comment by prat-man** [comment]
I found a simple solution to my problem.

```
// select the text
codeArea.selectRange(start, end);

// scroll to selection
codeArea.scrollXToPixel(0);
codeArea.requestFollowCaret();
```

This works perfectly, by first scrolling to the very left, and then scrolling to the caret, making it always display the selection inside the viewport.

Thanks!
