### ISSUE TITLE
Question: Can I define my custom Paragraph breaks instead of "\n"?

### ISSUE THREAD

**Issue by Khalid3e** [FXMisc/RichTextFX#970]
Hi, I am using CodeArea with highlighting as provided in `JavaKeywordsDemo.java`, highlighting works fine as expected, except for multi-line comment **if it actually has multi lines**

_Yes!_
![image](https://user-images.githubusercontent.com/37152435/95461338-04696280-096e-11eb-8a7e-e075922ee501.png)

_No!_
![image](https://user-images.githubusercontent.com/37152435/95461398-15b26f00-096e-11eb-8f35-32f7a6b00e49.png) 

_No!_
![image](https://user-images.githubusercontent.com/37152435/95474493-11418280-097d-11eb-8cf7-84636b7d4723.png)

**My take on it:** 
I think a Paragraph by docs' definition is 

> It corresponds to a single line when the text is not wrapped or spans multiple lines when the text is wrapped.

Also, I know that `VisibleParagraphStyler,accept()` does the highlighting by paragraphs, so it fails here to gather all the comment lines as one paragraph since there are line breaks between them.

**My question:**
Is it possible to for paragraphs start/end to be defined by a custom chars like `;` `/*` `*/`  `//` other than a "\n"? Are there any suggested workarounds since I've seen multiple projects using RichText (like [OmniEditor](https://github.com/giancosta86/OmniEditor)) and they are highlighting multi-lines comments successfully.

**Comment by Jugen** [comment]
So the `JavaKeywordsDemo` was recently updated with a way to only compute highlighting on the visible paragraphs instead of on the whole contents of the editor. However the regular expression pattern for comments was originally designed to work on a block of text and not lines of text, which is why the multi-line comments aren't being correctly styled (when using the visible paragraphs highlighting method).

To fix this just add `+ "|/\\*[^\\v]*|^\\h*\\*([^\\v]*|/)";` to the current COMMENT_PATTERN and it should highlight correctly again.

I'll also submit a PR shortly to address this.
